### ISSUE TITLE
When a database file is opened from URL (WebDAV) then an error is shown when saving.

### ISSUE THREAD

**Issue by JasonLandbridge** [marvinweber/KPSimpleBackup#4]
Hi there, 

When this plugin is used locally then everything is working as intended but when it tries to backup a database opened from URL then the below error is shown. Ideally, it would create a backup folder on the online storage or make it possible to add an online storage location in the settings. 

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: Could not find a part of the path 'S:\Online\Passwords\KeePass\Database\Backups\Main_2019.08.09_11.59.58.kdbx.tmp'. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'S:\Online\Passwords\KeePass\Database\Backups\Main_2019.08.09_11.59.58.kdbx.tmp'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing)
   at System.Net.FileWebRequest.GetRequestStreamCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.OpenWrite(Uri address, String method)
   at KeePassLib.Serialization.IOConnection.OpenWrite(IOConnectionInfo ioc)
   at KeePassLib.PwDatabase.Save(IStatusLogger slLogger)
   at KeePassLib.PwDatabase.SaveAs(IOConnectionInfo ioConnection, Boolean bIsPrimaryNow, IStatusLogger slLogger)
   at KPSimpleBackup.KPSimpleBackupExt.BackupAction(PwDatabase database)
   at KPSimpleBackup.KPSimpleBackupExt.OnSaveAction(Object sender, FileSavedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at KeePass.Forms.MainForm.SaveDatabase(PwDatabase pdToSave, Object sender)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at KeePass.UI.CustomToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.41.0.19744
    Win32 Version: 2.41.0.0
    CodeBase: file:///D:/Install/KeePass/KeePass.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3429.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
AutoTypeSearch
    Assembly Version: 2.27.0.0
    Win32 Version: 0.11.0.0
    CodeBase: file:///C:/Users/Jason/AppData/Local/KeePass/PluginCache/tiwjnSaTexPjUNkuKz5R/AutoTypeSearch.dll
----------------------------------------
HaveIBeenPwned
    Assembly Version: 1.3.1.0
    Win32 Version: 1.3.1.0
    CodeBase: file:///C:/Users/Jason/AppData/Local/KeePass/PluginCache/cGtcnWFvXLvBLeo1NMz7/HaveIBeenPwned.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
KeePassFaviconDownloader
    Assembly Version: 2.0.9.36531
    Win32 Version: 1.9.0.0
    CodeBase: file:///C:/Users/Jason/AppData/Local/KeePass/PluginCache/xELOlrAHW8sX1ELuPChO/KeePassFaviconDownloader.dll
----------------------------------------
KeePassRPC
    Assembly Version: 2.0.34.36533
    Win32 Version: 1.8.0.0
    CodeBase: file:///C:/Users/Jason/AppData/Local/KeePass/PluginCache/8UsRMUrfthPScL1EQMLm/KeePassRPC.dll
----------------------------------------
Fleck2
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Jason/AppData/Local/KeePass/PluginCache/8UsRMUrfthPScL1EQMLm/Fleck2.DLL
----------------------------------------
DomainPublicSuffix
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///C:/Users/Jason/AppData/Local/KeePass/PluginCache/8UsRMUrfthPScL1EQMLm/DomainPublicSuffix.DLL
----------------------------------------
Jayrock
    Assembly Version: 0.9.12915.0
    Win32 Version: 0.9.11214.1056
    CodeBase: file:///C:/Users/Jason/AppData/Local/KeePass/PluginCache/8UsRMUrfthPScL1EQMLm/Jayrock.DLL
----------------------------------------
KPSimpleBackup
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/Jason/AppData/Local/KeePass/PluginCache/0C2HbbVxUDZFsBTCDRdD/KPSimpleBackup.dll
----------------------------------------
PEDCalc
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1
    CodeBase: file:///C:/Users/Jason/AppData/Local/KeePass/PluginCache/wqY77b9AWupgUjEtLLEn/PEDCalc.dll
----------------------------------------
YetAnotherFaviconDownloader
    Assembly Version: 1.2.1.0
    Win32 Version: 1.2.1.0
    CodeBase: file:///C:/Users/Jason/AppData/Local/KeePass/PluginCache/adwxJf6SKE2AYsYLQNzK/YetAnotherFaviconDownloader.dll
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.41.0.19744
    Win32 Version: 2.41.0.19744
    CodeBase: file:///D:/Install/KeePass/KeePass.XmlSerializers.DLL
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3101.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Jayrock.Json
    Assembly Version: 0.9.12915.0
    Win32 Version: 0.9.13422.2206
    CodeBase: file:///C:/Users/Jason/AppData/Local/KeePass/PluginCache/8UsRMUrfthPScL1EQMLm/Jayrock.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Windows.ApplicationModel
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/WINDOWS/system32/WinMetadata/Windows.ApplicationModel.winmd
----------------------------------------
System.Runtime.InteropServices.WindowsRuntime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.WindowsRuntime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.WindowsRuntime.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by weberonede** [comment]
Hey, thank you for reporting this issue :)

Can you specify the problem a little bit, please?
Are you trying to backup to a cloud-(storage) / URL / etc. If so, how are you trying to do that. Or are you trying to backup a local database on a network-drive, etc.?

Thanks for the additional information! :)

**Comment by marvinweber** [comment]
After looking at the exception again i guess you have not created the backup directory. The plugin currently does not ensure, that the backup-path is available, so you have to create all necessary folders by yourself.

**Comment by JasonLandbridge** [comment]
Apologies for the long wait, I have indeed a network drive that is used as an backup location. 

I used to open my KDBX file from a network location and KPSimpleBackup would store it there without problems. But recently I have hosted my KDBX file on my NAS and communicate with it through WebDav. This works fine but then KPSimpleBackup gives the above exception when it cannot find the network location when i'm away from my home network. 

Could the plugin check for the existence of a backup location and/or provide some cloud integration features?

**Comment by marvinweber** [comment]
So if the only problem is the exception you get, when the plugin does not find the backup location, please test it again with the latest version of KPSimpleBackup. Exceptions are not shown anymore but catched and "logged", so you at least won't get the error message when the directory is not found.

Checking for the existance of the folder does, indeed, make sense and i will look into it :)

**Comment by marvinweber** [comment]
**FYI**: Starting with the next release  of KPSimpleBackup ([Version 1.3](https://github.com/marvinweber/KPSimpleBackup/milestone/1)) it will check if the backup location is available and try to create it if not.  
If the creation fails or is not possible, a warning is shown in the info bar of KeePass (at the bottom) and the corresponding backup path is skipped.
