### ISSUE TITLE
Database backup error

### ISSUE THREAD

**Issue by nollinvoyd** [marvinweber/KPSimpleBackup#53]
Tried to do a save today, and this error occurred.  Up to then, everything was working normally, and no changes were made to the Keepass configuration  prior to this event.

![KEEPASS](https://github.com/marvinweber/KPSimpleBackup/assets/20844322/9fb765a1-d2bd-4c3d-a85a-3bc3b54542b4)

I have the log if you need to see it.

**Comment by marvinweber** [comment]
Hi, yes it would be helpful to see the logs.

Just make sure to remove any sensitive information. Thx!

**Comment by nollinvoyd** [comment]
I also wanted to mention that after the save attempt, this progress bar remained running until I closed Keepqass

![KEEPASS](https://github.com/marvinweber/KPSimpleBackup/assets/20844322/236bab2b-0276-4da7-9d19-1d7333bd5847)

I thought perhaps the cause might be attributed to the fact that my virtual Google drive was not mounted, but it did not solve the problem

Log:

`[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Info] KPSimpleBackup: Backup started...
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Info] START BackupManager: BasicBackup for database: 
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Info] Backup to next path: Z:/Other computers/My Computer/GOOGLE DRIVE/
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Error] Could not create backup directory!
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [AdditionalInfo] Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'Z:/Other computers/My Computer/GOOGLE DRIVE/'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at KPSimpleBackup.BasicBackupManager.PreBackup()
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [AdditionalInfo] BackupManager (BasicBackup) finished with warnings!
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [AdditionalInfo] Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'Z:/Other computers/My Computer/GOOGLE DRIVE/'.
   at KPSimpleBackup.BasicBackupManager.PreBackup()
   at KPSimpleBackup.BackupManager.Run()
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Info] Backup to next path: N:/KeePass2 DATABASE BACKUP/
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Info] Save database to: file:///N:/KeePass2 DATABASE BACKUP/NewDatabase_7/11/2023 5:02:26 PM.kdbx
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [AdditionalInfo] BackupManager (BasicBackup) finished with warnings!
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [AdditionalInfo] Exception: System.Net.WebException: The given path's format is not supported. ---> System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing)
   at System.Net.FileWebRequest.GetRequestStreamCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.OpenWrite(Uri address, String method)
   at KeePassLib.Serialization.IOConnection.OpenWrite(IOConnectionInfo ioc)
   at KeePassLib.PwDatabase.Save(IStatusLogger slLogger)
   at KeePassLib.PwDatabase.SaveAs(IOConnectionInfo ioConnection, Boolean bIsPrimaryNow, IStatusLogger slLogger)
   at KPSimpleBackup.BackupManager.SavePwDatabaseToPath(IOConnectionInfo fileInfo)
   at KPSimpleBackup.BackupManager.SavePwDatabaseToPath(String path)
   at KPSimpleBackup.BasicBackupManager.Backup()
   at KPSimpleBackup.BackupManager.Run()
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Info] Backup to next path: N:/ONEDRIVE/NEWDATABASE/
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Info] Save database to: file:///N:/ONEDRIVE/NEWDATABASE/NewDatabase_7/11/2023 5:02:26 PM.kdbx
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [AdditionalInfo] BackupManager (BasicBackup) finished with warnings!
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [AdditionalInfo] Exception: System.Net.WebException: The given path's format is not supported. ---> System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing)
   at System.Net.FileWebRequest.GetRequestStreamCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.OpenWrite(Uri address, String method)
   at KeePassLib.Serialization.IOConnection.OpenWrite(IOConnectionInfo ioc)
   at KeePassLib.PwDatabase.Save(IStatusLogger slLogger)
   at KeePassLib.PwDatabase.SaveAs(IOConnectionInfo ioConnection, Boolean bIsPrimaryNow, IStatusLogger slLogger)
   at KPSimpleBackup.BackupManager.SavePwDatabaseToPath(IOConnectionInfo fileInfo)
   at KPSimpleBackup.BackupManager.SavePwDatabaseToPath(String path)
   at KPSimpleBackup.BasicBackupManager.Backup()
   at KPSimpleBackup.BackupManager.Run()
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Info] Backup to next path: N:/GOOGLE DRIVE/NEWDATABASE/
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Info] Save database to: file:///N:/GOOGLE DRIVE/NEWDATABASE/NewDatabase_7/11/2023 5:02:26 PM.kdbx
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [AdditionalInfo] BackupManager (BasicBackup) finished with warnings!
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [AdditionalInfo] Exception: System.Net.WebException: The given path's format is not supported. ---> System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing)
   at System.Net.FileWebRequest.GetRequestStreamCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.OpenWrite(Uri address, String method)
   at KeePassLib.Serialization.IOConnection.OpenWrite(IOConnectionInfo ioc)
   at KeePassLib.PwDatabase.Save(IStatusLogger slLogger)
   at KeePassLib.PwDatabase.SaveAs(IOConnectionInfo ioConnection, Boolean bIsPrimaryNow, IStatusLogger slLogger)
   at KPSimpleBackup.BackupManager.SavePwDatabaseToPath(IOConnectionInfo fileInfo)
   at KPSimpleBackup.BackupManager.SavePwDatabaseToPath(String path)
   at KPSimpleBackup.BasicBackupManager.Backup()
   at KPSimpleBackup.BackupManager.Run()
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Info] FINISHED BackupManager: BasicBackup
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Info] START BackupManager: KeePassConfigBackup for database: 
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Info] Backup to next path: Z:/Other computers/My Computer/GOOGLE DRIVE/
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Error] Could not create backup directory!
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [AdditionalInfo] Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'Z:/Other computers/My Computer/GOOGLE DRIVE/'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at KPSimpleBackup.KPConfigBackupManager.PreBackup()
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [AdditionalInfo] BackupManager (KeePassConfigBackup) finished with warnings!
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [AdditionalInfo] Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'Z:/Other computers/My Computer/GOOGLE DRIVE/'.
   at KPSimpleBackup.KPConfigBackupManager.PreBackup()
   at KPSimpleBackup.BackupManager.Run()
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Info] Backup to next path: N:/KeePass2 DATABASE BACKUP/
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Info] Skipping path, no configuration found at: C:\Users\mr\AppData\Roaming\KeePass\KeePass.config.xml
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Info] Copy N:\PortableApps.com Platform\PortableApps\KeePassProPortable\App\KeePassPro\KeePass.config.xml to N:\KeePass2 DATABASE BACKUP\KeePass.config.xml.backup-application-config_7\11\2023 5:02:26 PM
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Error] Could not backup KeePass configuration file!
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [AdditionalInfo] System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at Microsoft.VisualBasic.FileIO.FileSystem.NormalizePath(String Path)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyOrMoveFile(CopyOrMove operation, String sourceFileName, String destinationFileName, Boolean overwrite, UIOptionInternal showUI, UICancelOption onUserCancel)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyFile(String sourceFileName, String destinationFileName, Boolean overwrite)
   at KPSimpleBackup.KPConfigBackupManager.CopyConfig(String configPath, String suffix)
   at KPSimpleBackup.KPConfigBackupManager.Backup()
[7/11/2023 5:02:26 PM] [KPSimpleBackup] [Info] Backup to next path: N:/ONEDRIVE/NEWDATABASE/
[7/11/2023 5:02:27 PM] [KPSimpleBackup] [Info] Skipping path, no configuration found at: C:\Users\mr\AppData\Roaming\KeePass\KeePass.config.xml
[7/11/2023 5:02:27 PM] [KPSimpleBackup] [Info] Copy N:\PortableApps.com Platform\PortableApps\KeePassProPortable\App\KeePassPro\KeePass.config.xml to N:\ONEDRIVE\NEWDATABASE\KeePass.config.xml.backup-application-config_7\11\2023 5:02:27 PM
[7/11/2023 5:02:27 PM] [KPSimpleBackup] [Error] Could not backup KeePass configuration file!
[7/11/2023 5:02:27 PM] [KPSimpleBackup] [AdditionalInfo] System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at Microsoft.VisualBasic.FileIO.FileSystem.NormalizePath(String Path)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyOrMoveFile(CopyOrMove operation, String sourceFileName, String destinationFileName, Boolean overwrite, UIOptionInternal showUI, UICancelOption onUserCancel)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyFile(String sourceFileName, String destinationFileName, Boolean overwrite)
   at KPSimpleBackup.KPConfigBackupManager.CopyConfig(String configPath, String suffix)
   at KPSimpleBackup.KPConfigBackupManager.Backup()
[7/11/2023 5:02:27 PM] [KPSimpleBackup] [Info] Backup to next path: N:/GOOGLE DRIVE/NEWDATABASE/
[7/11/2023 5:02:27 PM] [KPSimpleBackup] [Info] Skipping path, no configuration found at: C:\Users\mr\AppData\Roaming\KeePass\KeePass.config.xml
[7/11/2023 5:02:27 PM] [KPSimpleBackup] [Info] Copy N:\PortableApps.com Platform\PortableApps\KeePassProPortable\App\KeePassPro\KeePass.config.xml to N:\GOOGLE DRIVE\NEWDATABASE\KeePass.config.xml.backup-application-config_7\11\2023 5:02:27 PM
[7/11/2023 5:02:27 PM] [KPSimpleBackup] [Error] Could not backup KeePass configuration file!
[7/11/2023 5:02:27 PM] [KPSimpleBackup] [AdditionalInfo] System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at Microsoft.VisualBasic.FileIO.FileSystem.NormalizePath(String Path)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyOrMoveFile(CopyOrMove operation, String sourceFileName, String destinationFileName, Boolean overwrite, UIOptionInternal showUI, UICancelOption onUserCancel)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyFile(String sourceFileName, String destinationFileName, Boolean overwrite)
   at KPSimpleBackup.KPConfigBackupManager.CopyConfig(String configPath, String suffix)
   at KPSimpleBackup.KPConfigBackupManager.Backup()
[7/11/2023 5:02:27 PM] [KPSimpleBackup] [Info] FINISHED BackupManager: KeePassConfigBackup
[7/11/2023 5:02:30 PM] [KPSimpleBackup] [Info] KPSimpleBackup: Finished in 3400 ms.
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] KPSimpleBackup: Backup started...
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] START BackupManager: BasicBackup for database: 
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] Backup to next path: Z:/Other computers/My Computer/GOOGLE DRIVE/
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Error] Could not create backup directory!
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [AdditionalInfo] Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'Z:/Other computers/My Computer/GOOGLE DRIVE/'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at KPSimpleBackup.BasicBackupManager.PreBackup()
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [AdditionalInfo] BackupManager (BasicBackup) finished with warnings!
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [AdditionalInfo] Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'Z:/Other computers/My Computer/GOOGLE DRIVE/'.
   at KPSimpleBackup.BasicBackupManager.PreBackup()
   at KPSimpleBackup.BackupManager.Run()
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] Backup to next path: N:/KeePass2 DATABASE BACKUP/
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] Save database to: file:///N:/KeePass2 DATABASE BACKUP/NewDatabase_7/11/2023 5:02:33 PM.kdbx
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [AdditionalInfo] BackupManager (BasicBackup) finished with warnings!
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [AdditionalInfo] Exception: System.Net.WebException: The given path's format is not supported. ---> System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing)
   at System.Net.FileWebRequest.GetRequestStreamCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.OpenWrite(Uri address, String method)
   at KeePassLib.Serialization.IOConnection.OpenWrite(IOConnectionInfo ioc)
   at KeePassLib.PwDatabase.Save(IStatusLogger slLogger)
   at KeePassLib.PwDatabase.SaveAs(IOConnectionInfo ioConnection, Boolean bIsPrimaryNow, IStatusLogger slLogger)
   at KPSimpleBackup.BackupManager.SavePwDatabaseToPath(IOConnectionInfo fileInfo)
   at KPSimpleBackup.BackupManager.SavePwDatabaseToPath(String path)
   at KPSimpleBackup.BasicBackupManager.Backup()
   at KPSimpleBackup.BackupManager.Run()
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] Backup to next path: N:/ONEDRIVE/NEWDATABASE/
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] Save database to: file:///N:/ONEDRIVE/NEWDATABASE/NewDatabase_7/11/2023 5:02:33 PM.kdbx
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [AdditionalInfo] BackupManager (BasicBackup) finished with warnings!
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [AdditionalInfo] Exception: System.Net.WebException: The given path's format is not supported. ---> System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing)
   at System.Net.FileWebRequest.GetRequestStreamCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.OpenWrite(Uri address, String method)
   at KeePassLib.Serialization.IOConnection.OpenWrite(IOConnectionInfo ioc)
   at KeePassLib.PwDatabase.Save(IStatusLogger slLogger)
   at KeePassLib.PwDatabase.SaveAs(IOConnectionInfo ioConnection, Boolean bIsPrimaryNow, IStatusLogger slLogger)
   at KPSimpleBackup.BackupManager.SavePwDatabaseToPath(IOConnectionInfo fileInfo)
   at KPSimpleBackup.BackupManager.SavePwDatabaseToPath(String path)
   at KPSimpleBackup.BasicBackupManager.Backup()
   at KPSimpleBackup.BackupManager.Run()
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] Backup to next path: N:/GOOGLE DRIVE/NEWDATABASE/
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] Save database to: file:///N:/GOOGLE DRIVE/NEWDATABASE/NewDatabase_7/11/2023 5:02:33 PM.kdbx
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [AdditionalInfo] BackupManager (BasicBackup) finished with warnings!
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [AdditionalInfo] Exception: System.Net.WebException: The given path's format is not supported. ---> System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing)
   at System.Net.FileWebRequest.GetRequestStreamCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.OpenWrite(Uri address, String method)
   at KeePassLib.Serialization.IOConnection.OpenWrite(IOConnectionInfo ioc)
   at KeePassLib.PwDatabase.Save(IStatusLogger slLogger)
   at KeePassLib.PwDatabase.SaveAs(IOConnectionInfo ioConnection, Boolean bIsPrimaryNow, IStatusLogger slLogger)
   at KPSimpleBackup.BackupManager.SavePwDatabaseToPath(IOConnectionInfo fileInfo)
   at KPSimpleBackup.BackupManager.SavePwDatabaseToPath(String path)
   at KPSimpleBackup.BasicBackupManager.Backup()
   at KPSimpleBackup.BackupManager.Run()
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] FINISHED BackupManager: BasicBackup
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] START BackupManager: KeePassConfigBackup for database: 
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] Backup to next path: Z:/Other computers/My Computer/GOOGLE DRIVE/
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Error] Could not create backup directory!
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [AdditionalInfo] Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'Z:/Other computers/My Computer/GOOGLE DRIVE/'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at KPSimpleBackup.KPConfigBackupManager.PreBackup()
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [AdditionalInfo] BackupManager (KeePassConfigBackup) finished with warnings!
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [AdditionalInfo] Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'Z:/Other computers/My Computer/GOOGLE DRIVE/'.
   at KPSimpleBackup.KPConfigBackupManager.PreBackup()
   at KPSimpleBackup.BackupManager.Run()
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] Backup to next path: N:/KeePass2 DATABASE BACKUP/
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] Skipping path, no configuration found at: C:\Users\mr\AppData\Roaming\KeePass\KeePass.config.xml
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] Copy N:\PortableApps.com Platform\PortableApps\KeePassProPortable\App\KeePassPro\KeePass.config.xml to N:\KeePass2 DATABASE BACKUP\KeePass.config.xml.backup-application-config_7\11\2023 5:02:33 PM
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Error] Could not backup KeePass configuration file!
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [AdditionalInfo] System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at Microsoft.VisualBasic.FileIO.FileSystem.NormalizePath(String Path)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyOrMoveFile(CopyOrMove operation, String sourceFileName, String destinationFileName, Boolean overwrite, UIOptionInternal showUI, UICancelOption onUserCancel)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyFile(String sourceFileName, String destinationFileName, Boolean overwrite)
   at KPSimpleBackup.KPConfigBackupManager.CopyConfig(String configPath, String suffix)
   at KPSimpleBackup.KPConfigBackupManager.Backup()
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] Backup to next path: N:/ONEDRIVE/NEWDATABASE/
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] Skipping path, no configuration found at: C:\Users\mr\AppData\Roaming\KeePass\KeePass.config.xml
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] Copy N:\PortableApps.com Platform\PortableApps\KeePassProPortable\App\KeePassPro\KeePass.config.xml to N:\ONEDRIVE\NEWDATABASE\KeePass.config.xml.backup-application-config_7\11\2023 5:02:33 PM
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Error] Could not backup KeePass configuration file!
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [AdditionalInfo] System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at Microsoft.VisualBasic.FileIO.FileSystem.NormalizePath(String Path)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyOrMoveFile(CopyOrMove operation, String sourceFileName, String destinationFileName, Boolean overwrite, UIOptionInternal showUI, UICancelOption onUserCancel)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyFile(String sourceFileName, String destinationFileName, Boolean overwrite)
   at KPSimpleBackup.KPConfigBackupManager.CopyConfig(String configPath, String suffix)
   at KPSimpleBackup.KPConfigBackupManager.Backup()
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] Backup to next path: N:/GOOGLE DRIVE/NEWDATABASE/
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] Skipping path, no configuration found at: C:\Users\mr\AppData\Roaming\KeePass\KeePass.config.xml
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] Copy N:\PortableApps.com Platform\PortableApps\KeePassProPortable\App\KeePassPro\KeePass.config.xml to N:\GOOGLE DRIVE\NEWDATABASE\KeePass.config.xml.backup-application-config_7\11\2023 5:02:33 PM
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Error] Could not backup KeePass configuration file!
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [AdditionalInfo] System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at Microsoft.VisualBasic.FileIO.FileSystem.NormalizePath(String Path)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyOrMoveFile(CopyOrMove operation, String sourceFileName, String destinationFileName, Boolean overwrite, UIOptionInternal showUI, UICancelOption onUserCancel)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyFile(String sourceFileName, String destinationFileName, Boolean overwrite)
   at KPSimpleBackup.KPConfigBackupManager.CopyConfig(String configPath, String suffix)
   at KPSimpleBackup.KPConfigBackupManager.Backup()
[7/11/2023 5:02:33 PM] [KPSimpleBackup] [Info] FINISHED BackupManager: KeePassConfigBackup
[7/11/2023 5:02:35 PM] [KPSimpleBackup] [Info] KPSimpleBackup: Finished in 2030 ms.
`

.

**Comment by marvinweber** [comment]
It looks like the path is not available / could not be found. Can you verify if backing up to a local folder does work?

Also, please check if the selected path for backups is available (in the Explorer) - did this error occur only once, or does backing up generally not work anymore?

**Comment by nollinvoyd** [comment]
Here's my previous settings

![keepass2](https://github.com/marvinweber/KPSimpleBackup/assets/20844322/740c65ce-2e47-480a-9b77-5f3561170b4f)

Now, with the virtual drive removed

![keepass](https://github.com/marvinweber/KPSimpleBackup/assets/20844322/44a041e8-f6b3-4466-99da-f74a50aad12d)

The N:/ drive related entries are local directories.

After removing the Z:\ virtual drive, the error continues.

I also had two other similar backup plugins installed.  In case of conflict, to test, I removed them

Error continued.

I tried these 3 configurations

![keepass6](https://github.com/marvinweber/KPSimpleBackup/assets/20844322/4279e6af-6f92-4aed-8a76-620b3ef8e295)

![keepass4](https://github.com/marvinweber/KPSimpleBackup/assets/20844322/6e6502cc-40c9-4f48-8c60-f31ce9adce09)

![keepass5](https://github.com/marvinweber/KPSimpleBackup/assets/20844322/8b505778-c521-40bb-93bf-d2ac6adced11)

Same result.

The backup to my local N:\KeePass2 DATABASE BACKUP directory is successful.  

OneDrive, Google Drive, and virtual Z:\ drive unsuccessful.

**Comment by nollinvoyd** [comment]
I'm also now getting this after logging in, even after removing the plugin.  I suppose it's has to do with me trying to activate the related setting.  How can i stop it?

![keepass](https://github.com/marvinweber/KPSimpleBackup/assets/20844322/7ade892b-5eae-491e-b8a7-2b5f23a9e23f)

**Comment by marvinweber** [comment]
> I'm also now getting this after logging in, even after removing the plugin. I suppose it's has to do with me trying to activate the related setting. How can i stop it?

This dialog is not from the KPSimpleBackup plugin. Please refer to the help of whatever plugin this is coming from. It looks like a plugin named "KeePassSync".

Regarding your ongoing backup issues i would ask you to remove all backup folders and test with a single folder that is created (locally) and available. If you get errors with that folder, please send me again the log files so that I can try to figure out whats going on. Thx a lot!

If it's possible for you, you could test backups will all other plugins disabled to check whether they might have any negative influence on the backup process.
